name: update-flake-lock
on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * 0" # runs weekly on Sunday at 00:00
defaults:
  run:
    shell: bash --noprofile --norc -exo pipefail {0}
env:
  REPO: aarnphm/dix
  GIT_AUTHOR_NAME: github-actions[bot]
  GIT_AUTHOR_EMAIL: github-actions[bot]@users.noreply.github.com
jobs:
  lockfile:
    if: github.repository_owner == 'aarnphm'
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Install jq, curl
        run: sudo apt-get install -y jq curl
      - name: Install Nix
        uses: cachix/install-nix-action@v22
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
      - name: lock the thing
        run: nix flake update
      - name: Get infos
        id: meta
        run: |
          echo "sha=$(curl -SsL "https://api.github.com/repos/${{ env.REPO }}/commits/main" | jq -r ".sha")" >> $GITHUB_OUTPUT
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "chore(lockfile): auto update flake.lock [${{ steps.meta.outputs.sha }}]"
          commit_user_name: ${{ env.GIT_AUTHOR_NAME }}
          commit_user_email: ${{ env.GIT_AUTHOR_EMAIL }}
          commit_author: ${{ env.GIT_AUTHOR_NAME }} <${{ env.GIT_AUTHOR_EMAIL }}>
          file_pattern: "flake.lock"
          commit_options: "--signoff"
