name: update-flake-lock
on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 */2 * *" # runs every two days
defaults:
  run:
    shell: bash --noprofile --norc -exo pipefail {0}
env:
  REPO: aarnphm/dix
  GIT_AUTHOR_NAME: github-actions[bot]
  GIT_AUTHOR_EMAIL: github-actions[bot]@users.noreply.github.com
jobs:
  lockfile:
    if: github.repository_owner == 'aarnphm'
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # ratchet:actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
      - uses: cachix/install-nix-action@8887e596b4ee1134dae06b98d573bd674693f47c # ratchet:cachix/install-nix-action@v26
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
          nix_path: nixpkgs=channel:nixos-unstable
      - id: import-gpg
        uses: crazy-max/ghaction-import-gpg@01dd5d3ca463c7f10f7f4f7b4f177225ac661ee4 # ratchet:crazy-max/ghaction-import-gpg@v6
        with:
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.GPG_PASSPHRASE }}
          git_config_global: true
          git_user_signingkey: true
          git_commit_gpgsign: true
      - uses: webfactory/ssh-agent@dc588b651fe13675774614f8e6a936a468676387 # ratchet:webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
      - run: nix flake update --debug
      - id: meta
        run: |
          echo "sha=$(curl -SsL "https://api.github.com/repos/${{ env.REPO }}/commits/main" | jq -r ".sha")" >> $GITHUB_OUTPUT
      - run: |
          git add flake.lock
          git commit -S -sm "chore(lockfile): auto update flake.lock [${{ steps.meta.outputs.sha }}]"
          git push origin main
